# Generated by Django 5.2.12 on 2026-03-26 06:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("event", models.CharField(db_index=True, max_length=255)),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
